package com.freelance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DeliveryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryAllPropertiesEquals(Delivery expected, Delivery actual) {
        assertDeliveryAutoGeneratedPropertiesEquals(expected, actual);
        assertDeliveryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryAllUpdatablePropertiesEquals(Delivery expected, Delivery actual) {
        assertDeliveryUpdatableFieldsEquals(expected, actual);
        assertDeliveryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryAutoGeneratedPropertiesEquals(Delivery expected, Delivery actual) {
        assertThat(actual)
            .as("Verify Delivery auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryUpdatableFieldsEquals(Delivery expected, Delivery actual) {
        assertThat(actual)
            .as("Verify Delivery relevant properties")
            .satisfies(a -> assertThat(a.getNote()).as("check note").isEqualTo(expected.getNote()))
            .satisfies(a -> assertThat(a.getDeliveredAt()).as("check deliveredAt").isEqualTo(expected.getDeliveredAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDeliveryUpdatableRelationshipsEquals(Delivery expected, Delivery actual) {
        assertThat(actual)
            .as("Verify Delivery relationships")
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()))
            .satisfies(a -> assertThat(a.getFile()).as("check file").isEqualTo(expected.getFile()));
    }
}
