package com.freelance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DisputeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeAllPropertiesEquals(Dispute expected, Dispute actual) {
        assertDisputeAutoGeneratedPropertiesEquals(expected, actual);
        assertDisputeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeAllUpdatablePropertiesEquals(Dispute expected, Dispute actual) {
        assertDisputeUpdatableFieldsEquals(expected, actual);
        assertDisputeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeAutoGeneratedPropertiesEquals(Dispute expected, Dispute actual) {
        assertThat(actual)
            .as("Verify Dispute auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeUpdatableFieldsEquals(Dispute expected, Dispute actual) {
        assertThat(actual)
            .as("Verify Dispute relevant properties")
            .satisfies(a -> assertThat(a.getReason()).as("check reason").isEqualTo(expected.getReason()))
            .satisfies(a -> assertThat(a.getOpenedAt()).as("check openedAt").isEqualTo(expected.getOpenedAt()))
            .satisfies(a -> assertThat(a.getClosedAt()).as("check closedAt").isEqualTo(expected.getClosedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDisputeUpdatableRelationshipsEquals(Dispute expected, Dispute actual) {
        assertThat(actual)
            .as("Verify Dispute relationships")
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()));
    }
}
