package com.freelance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FavoriteOfferAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteOfferAllPropertiesEquals(FavoriteOffer expected, FavoriteOffer actual) {
        assertFavoriteOfferAutoGeneratedPropertiesEquals(expected, actual);
        assertFavoriteOfferAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteOfferAllUpdatablePropertiesEquals(FavoriteOffer expected, FavoriteOffer actual) {
        assertFavoriteOfferUpdatableFieldsEquals(expected, actual);
        assertFavoriteOfferUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteOfferAutoGeneratedPropertiesEquals(FavoriteOffer expected, FavoriteOffer actual) {
        assertThat(actual)
            .as("Verify FavoriteOffer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteOfferUpdatableFieldsEquals(FavoriteOffer expected, FavoriteOffer actual) {
        assertThat(actual)
            .as("Verify FavoriteOffer relevant properties")
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFavoriteOfferUpdatableRelationshipsEquals(FavoriteOffer expected, FavoriteOffer actual) {
        assertThat(actual)
            .as("Verify FavoriteOffer relationships")
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()))
            .satisfies(a -> assertThat(a.getOffer()).as("check offer").isEqualTo(expected.getOffer()));
    }
}
