package com.freelance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FileObjectAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileObjectAllPropertiesEquals(FileObject expected, FileObject actual) {
        assertFileObjectAutoGeneratedPropertiesEquals(expected, actual);
        assertFileObjectAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileObjectAllUpdatablePropertiesEquals(FileObject expected, FileObject actual) {
        assertFileObjectUpdatableFieldsEquals(expected, actual);
        assertFileObjectUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileObjectAutoGeneratedPropertiesEquals(FileObject expected, FileObject actual) {
        assertThat(actual)
            .as("Verify FileObject auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileObjectUpdatableFieldsEquals(FileObject expected, FileObject actual) {
        assertThat(actual)
            .as("Verify FileObject relevant properties")
            .satisfies(a -> assertThat(a.getBucket()).as("check bucket").isEqualTo(expected.getBucket()))
            .satisfies(a -> assertThat(a.getObjectKey()).as("check objectKey").isEqualTo(expected.getObjectKey()))
            .satisfies(a -> assertThat(a.getContentType()).as("check contentType").isEqualTo(expected.getContentType()))
            .satisfies(a -> assertThat(a.getFileSize()).as("check fileSize").isEqualTo(expected.getFileSize()))
            .satisfies(a -> assertThat(a.getChecksum()).as("check checksum").isEqualTo(expected.getChecksum()))
            .satisfies(a -> assertThat(a.getDurationSeconds()).as("check durationSeconds").isEqualTo(expected.getDurationSeconds()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFileObjectUpdatableRelationshipsEquals(FileObject expected, FileObject actual) {
        // empty method
    }
}
