package com.freelance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OfferTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferTypeAllPropertiesEquals(OfferType expected, OfferType actual) {
        assertOfferTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertOfferTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferTypeAllUpdatablePropertiesEquals(OfferType expected, OfferType actual) {
        assertOfferTypeUpdatableFieldsEquals(expected, actual);
        assertOfferTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferTypeAutoGeneratedPropertiesEquals(OfferType expected, OfferType actual) {
        assertThat(actual)
            .as("Verify OfferType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferTypeUpdatableFieldsEquals(OfferType expected, OfferType actual) {
        assertThat(actual)
            .as("Verify OfferType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferTypeUpdatableRelationshipsEquals(OfferType expected, OfferType actual) {
        assertThat(actual)
            .as("Verify OfferType relationships")
            .satisfies(a -> assertThat(a.getSubcategory()).as("check subcategory").isEqualTo(expected.getSubcategory()));
    }
}
