package com.freelance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OfferMediaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferMediaAllPropertiesEquals(OfferMedia expected, OfferMedia actual) {
        assertOfferMediaAutoGeneratedPropertiesEquals(expected, actual);
        assertOfferMediaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferMediaAllUpdatablePropertiesEquals(OfferMedia expected, OfferMedia actual) {
        assertOfferMediaUpdatableFieldsEquals(expected, actual);
        assertOfferMediaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferMediaAutoGeneratedPropertiesEquals(OfferMedia expected, OfferMedia actual) {
        assertThat(actual)
            .as("Verify OfferMedia auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferMediaUpdatableFieldsEquals(OfferMedia expected, OfferMedia actual) {
        assertThat(actual)
            .as("Verify OfferMedia relevant properties")
            .satisfies(a -> assertThat(a.getMediaKind()).as("check mediaKind").isEqualTo(expected.getMediaKind()))
            .satisfies(a -> assertThat(a.getIsPrimary()).as("check isPrimary").isEqualTo(expected.getIsPrimary()))
            .satisfies(a -> assertThat(a.getCaption()).as("check caption").isEqualTo(expected.getCaption()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferMediaUpdatableRelationshipsEquals(OfferMedia expected, OfferMedia actual) {
        assertThat(actual)
            .as("Verify OfferMedia relationships")
            .satisfies(a -> assertThat(a.getOffer()).as("check offer").isEqualTo(expected.getOffer()))
            .satisfies(a -> assertThat(a.getFile()).as("check file").isEqualTo(expected.getFile()));
    }
}
