package com.freelance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OfferReviewAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferReviewAllPropertiesEquals(OfferReview expected, OfferReview actual) {
        assertOfferReviewAutoGeneratedPropertiesEquals(expected, actual);
        assertOfferReviewAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferReviewAllUpdatablePropertiesEquals(OfferReview expected, OfferReview actual) {
        assertOfferReviewUpdatableFieldsEquals(expected, actual);
        assertOfferReviewUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferReviewAutoGeneratedPropertiesEquals(OfferReview expected, OfferReview actual) {
        assertThat(actual)
            .as("Verify OfferReview auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferReviewUpdatableFieldsEquals(OfferReview expected, OfferReview actual) {
        assertThat(actual)
            .as("Verify OfferReview relevant properties")
            .satisfies(a -> assertThat(a.getText()).as("check text").isEqualTo(expected.getText()))
            .satisfies(a -> assertThat(a.getRating()).as("check rating").isEqualTo(expected.getRating()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferReviewUpdatableRelationshipsEquals(OfferReview expected, OfferReview actual) {
        assertThat(actual)
            .as("Verify OfferReview relationships")
            .satisfies(a -> assertThat(a.getOffer()).as("check offer").isEqualTo(expected.getOffer()))
            .satisfies(a -> assertThat(a.getReviewer()).as("check reviewer").isEqualTo(expected.getReviewer()));
    }
}
