package com.freelance.app.domain;

import static com.freelance.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OfferPackageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferPackageAllPropertiesEquals(OfferPackage expected, OfferPackage actual) {
        assertOfferPackageAutoGeneratedPropertiesEquals(expected, actual);
        assertOfferPackageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferPackageAllUpdatablePropertiesEquals(OfferPackage expected, OfferPackage actual) {
        assertOfferPackageUpdatableFieldsEquals(expected, actual);
        assertOfferPackageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferPackageAutoGeneratedPropertiesEquals(OfferPackage expected, OfferPackage actual) {
        assertThat(actual)
            .as("Verify OfferPackage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferPackageUpdatableFieldsEquals(OfferPackage expected, OfferPackage actual) {
        assertThat(actual)
            .as("Verify OfferPackage relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getCurrency()).as("check currency").isEqualTo(expected.getCurrency()))
            .satisfies(a -> assertThat(a.getDeliveryDays()).as("check deliveryDays").isEqualTo(expected.getDeliveryDays()))
            .satisfies(a -> assertThat(a.getPackageTier()).as("check packageTier").isEqualTo(expected.getPackageTier()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOfferPackageUpdatableRelationshipsEquals(OfferPackage expected, OfferPackage actual) {
        assertThat(actual)
            .as("Verify OfferPackage relationships")
            .satisfies(a -> assertThat(a.getOffer()).as("check offer").isEqualTo(expected.getOffer()));
    }
}
