package com.freelance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProfileReviewAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileReviewAllPropertiesEquals(ProfileReview expected, ProfileReview actual) {
        assertProfileReviewAutoGeneratedPropertiesEquals(expected, actual);
        assertProfileReviewAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileReviewAllUpdatablePropertiesEquals(ProfileReview expected, ProfileReview actual) {
        assertProfileReviewUpdatableFieldsEquals(expected, actual);
        assertProfileReviewUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileReviewAutoGeneratedPropertiesEquals(ProfileReview expected, ProfileReview actual) {
        assertThat(actual)
            .as("Verify ProfileReview auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileReviewUpdatableFieldsEquals(ProfileReview expected, ProfileReview actual) {
        assertThat(actual)
            .as("Verify ProfileReview relevant properties")
            .satisfies(a -> assertThat(a.getText()).as("check text").isEqualTo(expected.getText()))
            .satisfies(a -> assertThat(a.getRating()).as("check rating").isEqualTo(expected.getRating()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProfileReviewUpdatableRelationshipsEquals(ProfileReview expected, ProfileReview actual) {
        assertThat(actual)
            .as("Verify ProfileReview relationships")
            .satisfies(a -> assertThat(a.getReviewer()).as("check reviewer").isEqualTo(expected.getReviewer()))
            .satisfies(a -> assertThat(a.getReviewee()).as("check reviewee").isEqualTo(expected.getReviewee()));
    }
}
