package com.freelance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RequirementAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementAllPropertiesEquals(Requirement expected, Requirement actual) {
        assertRequirementAutoGeneratedPropertiesEquals(expected, actual);
        assertRequirementAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementAllUpdatablePropertiesEquals(Requirement expected, Requirement actual) {
        assertRequirementUpdatableFieldsEquals(expected, actual);
        assertRequirementUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementAutoGeneratedPropertiesEquals(Requirement expected, Requirement actual) {
        assertThat(actual)
            .as("Verify Requirement auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementUpdatableFieldsEquals(Requirement expected, Requirement actual) {
        assertThat(actual)
            .as("Verify Requirement relevant properties")
            .satisfies(a -> assertThat(a.getPrompt()).as("check prompt").isEqualTo(expected.getPrompt()))
            .satisfies(a -> assertThat(a.getAnswer()).as("check answer").isEqualTo(expected.getAnswer()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRequirementUpdatableRelationshipsEquals(Requirement expected, Requirement actual) {
        assertThat(actual)
            .as("Verify Requirement relationships")
            .satisfies(a -> assertThat(a.getOrder()).as("check order").isEqualTo(expected.getOrder()));
    }
}
