package com.freelance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SubcategoryAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubcategoryAllPropertiesEquals(Subcategory expected, Subcategory actual) {
        assertSubcategoryAutoGeneratedPropertiesEquals(expected, actual);
        assertSubcategoryAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubcategoryAllUpdatablePropertiesEquals(Subcategory expected, Subcategory actual) {
        assertSubcategoryUpdatableFieldsEquals(expected, actual);
        assertSubcategoryUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubcategoryAutoGeneratedPropertiesEquals(Subcategory expected, Subcategory actual) {
        assertThat(actual)
            .as("Verify Subcategory auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubcategoryUpdatableFieldsEquals(Subcategory expected, Subcategory actual) {
        assertThat(actual)
            .as("Verify Subcategory relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getCreatedDate()).as("check createdDate").isEqualTo(expected.getCreatedDate()))
            .satisfies(a -> assertThat(a.getLastModifiedDate()).as("check lastModifiedDate").isEqualTo(expected.getLastModifiedDate()))
            .satisfies(a -> assertThat(a.getCreatedBy()).as("check createdBy").isEqualTo(expected.getCreatedBy()))
            .satisfies(a -> assertThat(a.getLastModifiedBy()).as("check lastModifiedBy").isEqualTo(expected.getLastModifiedBy()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSubcategoryUpdatableRelationshipsEquals(Subcategory expected, Subcategory actual) {
        assertThat(actual)
            .as("Verify Subcategory relationships")
            .satisfies(a -> assertThat(a.getCategory()).as("check category").isEqualTo(expected.getCategory()));
    }
}
