package com.freelance.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VerificationRequestAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationRequestAllPropertiesEquals(VerificationRequest expected, VerificationRequest actual) {
        assertVerificationRequestAutoGeneratedPropertiesEquals(expected, actual);
        assertVerificationRequestAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationRequestAllUpdatablePropertiesEquals(VerificationRequest expected, VerificationRequest actual) {
        assertVerificationRequestUpdatableFieldsEquals(expected, actual);
        assertVerificationRequestUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationRequestAutoGeneratedPropertiesEquals(VerificationRequest expected, VerificationRequest actual) {
        assertThat(actual)
            .as("Verify VerificationRequest auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationRequestUpdatableFieldsEquals(VerificationRequest expected, VerificationRequest actual) {
        // empty method

    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVerificationRequestUpdatableRelationshipsEquals(VerificationRequest expected, VerificationRequest actual) {
        assertThat(actual)
            .as("Verify VerificationRequest relationships")
            .satisfies(a -> assertThat(a.getProfile()).as("check profile").isEqualTo(expected.getProfile()))
            .satisfies(a -> assertThat(a.getFileObject()).as("check fileObject").isEqualTo(expected.getFileObject()));
    }
}
